# Generated by Django 4.2.7 on 2023-12-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='ad',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='soyad',
            new_name='time',
        ),
    ]
